# Q1

In [ ]:
import numpy as np
arr = np.arange(1, 13)
arr_2d = arr.reshape(3, 4)

print("数组维度ndim：", arr_2d.ndim)
print("数组形状shape：", arr_2d.shape)
print("元素总个数size：", arr_2d.size)

数组维度ndim： 2
数组形状shape： (3, 4)
元素总个数size： 12


# Q2

In [ ]:
import numpy as np
float_arr = np.array([1.5, 2.6, 3.7, 4.8])
int_arr = float_arr.astype(np.int32)

print("转换前的数组：", float_arr)
print("转换前数组的数据类型：", float_arr.dtype.name)
print("\n转换后的数组：", int_arr)
print("转换后数组的数据类型：", int_arr.dtype.name)

转换前的数组： [1.5 2.6 3.7 4.8]
转换前数组的数据类型： float64

转换后的数组： [1 2 3 4]
转换后数组的数据类型： int32


# Q3


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
first_two_rows = arr[:2, :] 
sub_arr = arr[:2, 1:3]

print("原数组：")
print(arr)
print("\n获取前两行：")
print(first_two_rows)
print("\n获取前两行 + 第2~3列：")
print(sub_arr)
print(arr[1: , 2:])

原数组：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

获取前两行：
[[1 2 3 4]
 [5 6 7 8]]

获取前两行 + 第2~3列：
[[2 3]
 [6 7]]
[[ 7  8]
 [11 12]]


# Q4

In [ ]:
import numpy as np
arr = np.array([10, 15, 20, 25, 30, 35])
fancy_result = arr[[0, 2, 4]]
bool_result = arr[arr > 20]

print("原数组：", arr)
print("\n花式索引提取结果：", fancy_result)
print("布尔索引提取结果：", bool_result)

原数组： [10 15 20 25 30 35]

花式索引提取结果： [10 20 30]
布尔索引提取结果： [25 30 35]


array([10, 15])

# Q5

In [ ]:
import numpy as np
arr_zeros = np.zeros((3, 4))
arr_b = np.array([1, 2, 3, 4])
result = arr_zeros + arr_b

print("全0数组 (3,4)：")
print(arr_zeros)
print("\n一维数组 arr_b：", arr_b)
print("\n广播相加后的结果：")
print(result)

全0数组 (3,4)：
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

一维数组 arr_b： [1 2 3 4]

广播相加后的结果：
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


# Q6

In [ ]:
import numpy as np
x = np.array([1, 4, 9, 16])
y = np.array([2, 1, 4, 5])
sqrt_x = np.sqrt(x)
result = np.maximum(sqrt_x, y)

print("数组 x：", x)
print("x 的平方根：", sqrt_x)
print("数组 y：", y)
print("对应位置最大值：", result)

数组 x： [ 1  4  9 16]
x 的平方根： [1. 2. 3. 4.]
数组 y： [2 1 4 5]
对应位置最大值： [2. 2. 4. 5.]


# Q7

In [ ]:
import numpy as np
arr = np.arange(24).reshape((2, 3, 4))
arr_transposed = arr.transpose((1, 0, 2))

print("原数组形状：", arr.shape)
print("轴转换后的数组形状：", arr_transposed.shape)

原数组形状： (2, 3, 4)
轴转换后的数组形状： (3, 2, 4)


# Q8

In [ ]:
import numpy as np
arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])
result = np.where(arr_con, arr_x, arr_y)

print("最终结果：", result)

最终结果： [1 6 7]


# Q9

In [ ]:
import numpy as np
arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])
mean_val = arr.mean()
arr_sorted = arr.copy()  
arr_sorted.sort(axis=0)

print("原数组：")
print(arr)
print("\n所有元素的平均值：", mean_val)
print("\n按列排序（axis=0）后的数组：")
print(arr_sorted)

原数组：
[[6 2 7]
 [3 6 2]
 [4 3 2]]

所有元素的平均值： 3.888888888888889

按列排序（axis=0）后的数组：
[[3 2 2]
 [4 3 2]
 [6 6 7]]


# Q10

In [ ]:
import numpy as np
np.random.seed(10)
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
dot_product = np.dot(A, B)

print("矩阵 A：")
print(A)
print("\n矩阵 B：")
print(B)
print("\n矩阵 A 和 B 的点积：")
print(dot_product)

矩阵 A：
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]

矩阵 B：
[[0.49850701 0.22479665]
 [0.19806286 0.76053071]]

矩阵 A 和 B 的点积：
[[0.38861894 0.18917279]
 [0.46418833 0.71193035]]
